; ============================================================================
; php.ini for Wampstack Builder
; ============================================================================

[PHP]
engine = On
short_open_tag = Off
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL
memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 60
date.timezone = "Europe/Brussels"

extension_dir = "__BASEDIR__/php/ext"

extension=curl
extension=exif
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=zip

[Session]
session.save_handler = files
